name: normacolor

services:
  mongo:
    image: mongodb/mongodb-atlas-local
    ports:
      - "1000:27017"
    volumes:
      - data:/var/lib/data/mongo

  redis:
    image: redis:alpine
    ports:
      - "1003:6379"
    volumes:
      - data:/var/lib/data/redis

volumes:
  data:
